version: '3.8'

services:
  frontend_next:
    image: nitinsaa1999/testproject-frontend_next
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - D:\Test Project\Frontend\Test-Frontend\test-frotnend:/app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
