version: '3.8'

services:
  frontend_next_dev:
    image: nitinsaa1999/testproject-frontend_next_dev
    container_name: nitin_frontend_dev
    working_dir: /app
    build:
      context: ./
      dockerfile: DockerfileDev
    volumes:
      - D:/Test Project/Frontend/Test-Frontend/test-frotnend:/app:rw
    env_file: ./.env.dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    restart: unless-stopped
    command: sleep infinity
#     networks:
#       - node-network
# networks: 
#   node-network:
#     external: true
