version: '3.8'

services:
  frontend_next_2:
    # image: nitinsaa1999/testproject-frontend_next_2
    working_dir: /app
    build:
      context: ./
      dockerfile: Dockerfile2
    volumes:
      - D:\Test Project\Frontend\Test-Frontend\test-frotnend:/app:rw
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    restart: unless-stopped
    command: sleep infinity
