version: '3.8'

services:
  frontend_next_prod:
    image: nitinsaa1999/testproject-frontend_next_prod
    container_name: nitin_frontend_prod
    working_dir: /app
    build:
      context: ./
      dockerfile: DockerfileProd
    # volumes:
    #   - D:\Test Project\Frontend:/app:rw
    env_file: ./.env.prod
    environment:
      NODE_ENV: production
    ports:
      - 3002:3000
    restart: unless-stopped
    command: sleep infinity
    networks:
      - node-network

  nginx_prod:
    image: nitinsaa1999/testproject-backend_nginx_prod
    container_name: nitin_nginx_prod
    build:
      context: D:\Test Project\proxyServer
      dockerfile: DockerfileProd
    ports:
      - "10002:80"
    volumes:
      - D:\Test Project\proxyServer\nginx.prod.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - frontend_next_prod
    networks:
      - node-network
networks: 
  node-network:
    driver: bridge
